trigger:
  - master

variables:
  versionprefix: 0.1.0

jobs:
  - job: 'BuildPackage'
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-18.04'
          rid: 'linux-x64'
        mac:
          imageName: 'macos-10.14'
          rid: 'osx-x64'
        windows:
          rid: 'windows-x64'
          imageName: 'windows-2019'

    pool:
      vmImage: $(imageName)

    variables:
      buildConfiguration: 'Release'

    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          packageType: sdk
          version: 3.1.201
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: CmdLine@2
        displayName: 'Install linux dependencies'
        condition: eq(variables.rid, 'linux-x64')
        inputs:
          script: 'sudo apt-get update && sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev'
      - task: CmdLine@2
          condition: eq(variables.rid, 'osx-x64')
          displayName: 'dotnet pack SpiderEye.Mac'
          inputs:
            script: 'dotnet pack -c $(buildConfiguration) Source/SpiderEye.Mac/SpiderEye.Mac.csproj /p:VersionPrefix=$(versionprefix) /p:VersionSuffix=$(Build.BuildNumber)'
      - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'artifacts'
              ArtifactName: 'artifacts-$(rid)'
              publishLocation: 'Container'
